export interface Category { id: string; name: string; slug: string; description: string }
export interface Product { id: string; slug: string; name: string; shortDescription: string; description: string; brand: string; sku: string; price: string; salePrice: string | null; stock: number; status: string; featured: boolean; thumbnail: string; sizes: string[]; colors: string[]; shippingInfo: string; returnPolicy: string; categories: Category[]; images: { id: string; url: string; alt: string }[] }
export interface CartItem { id: string; quantity: number; selectedSize: string; selectedColor: string; unitPrice: number; lineTotal: number; product: Product }
export interface Cart { id: string; items: CartItem[]; appliedOfferCode?: string | null; appliedOffer?: any; totals: { subtotal: number; discount: number; offerDiscount: number; shipping: number; tax: number; grandTotal: number }; shipping?: { baseShippingFee?: number; freeShippingThreshold?: number; freeShippingEligible?: boolean; effectiveBaseShipping?: number; shippingStatus?: "NOT_SELECTED" | "CONFIRMED"; selectedOptionBreakdown?: any; [key: string]: any }; currency: string; deliveryOptionId?: string | null; deliveryOptions?: any[]; deliveryAddressId?: string | null }

export interface Address { id?: string; fullName: string; phone: string; line1: string; line2: string; landmark: string; town: string; city: string; district: string; state: string; pinCode: string; country: string; latitude: number | null; longitude: number | null; formattedAddress: string | null; isDefault: boolean }
export interface OrderItem { id: string; productId: string; productNameSnapshot: string; productImageSnapshot: string; selectedSize: string; selectedColor: string; quantity: number; unitPriceSnapshot: string }
export interface Order { id: string; orderNumber: string; createdAt: string; updatedAt: string; subtotal: string; discount: string; shippingCharge: string; tax: string; grandTotal: string; shippingAddressSnapshot: Address; deliverySnapshot?: any; paymentMethod: string; paymentStatus: string; orderStatus: string; trackingNumber: string | null; courierName: string | null; items: OrderItem[]; cancellation?: { status: string; reason: string; adminResponse?: string }; returns?: { id: string; returnNumber: string; status: string; reason: string; adminResponse?: string; history?: { status: string; createdAt: string; note?: string }[] }[]; offerRedemptions?: { offerCode: string; offerName: string; discountType: string; discountValue: number; actualDiscountAmount: number }[] }
export interface StoreData { store: { email: string; phone: string; whatsapp: string; whatsappMessage: string; whatsappEnabled: boolean; currency: string; returnPolicy: string; cancellationPolicy: string; privacyPolicy: string; terms: string; isOpen: boolean; returnsEnabled: boolean; requireReturnReason: boolean; allowReturnComment: boolean; requirePhotoForDamage: boolean; allowPartialReturns: boolean; allowedReturnResolutions: string; returnExpiredMessage: string; returnWindowMinutes: number; socialProfiles: string }; branding: { storeName: string; logo: string; headerLogo: string; footerLogo: string; favicon: string; tagline: string; storeDescription: string; heroHeading: string; heroSubheading: string; heroImage: string; heroButtonText: string; heroButtonLink: string; promotionalBanner: string; newsletterHeading: string; newsletterText: string }; location: { branchName: string; line1: string; line2: string; landmark: string; city: string; district: string; state: string; country: string; pinCode: string; latitude: number | null; longitude: number | null; mapsUrl: string; placeId?: string } }
